apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: 'softtekcoeapisms/shippingservice:1.0'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    name: shippingservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: shippingservice
  type: ClusterIP
